// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rizhddmdzxndmqaastbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpemhkZG1kenhuZG1xYWFzdGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDMxOTYsImV4cCI6MjA2MTA3OTE5Nn0.a69NC6MXXkYapS5txGPvQwl_Ca7YZjfQQm4UhuhBoTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);